kind: Run
apiVersion: garden.io/v2
name: init_prometheus
description: Prometheus storage initialization
type: container

spec:
  image: docker.io/prom/prometheus
  command: ["/bin/sh", "-c", "chown -R 65534:65534 /prometheus"]
  volumes:
    - name: data
      containerPath: /prometheus
      sourcePath: ${var.config-path}/prometheus/data
  user: root
